version: '2.4'

services:
  api:
    build: 
      context: .
    container_name: "scim-api"
    ports: 
      - 6000:80
      - 6001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Token:TokenAudience=8adf8e6e-67b2-4cf2-a259-e3dc5476c621
      - Token:TokenIssuer=docker-compose
      - Token:IssuerSigningKey=0ofmokgw6do9edfwkxb0w7mcudpbbqu3
      - Token:TokenLifetimeInMins=120
      - Logging:LogLevel:Default=Information
      - Logging:LogLevel:Microsoft=Warning
      - Logging:LogLevel:Microsoft.Hosting.Lifetime=Information

# {
#   "Logging": {
#     "LogLevel": {
#       "Default": "Information",
#       "Microsoft": "Warning",
#       "Microsoft.Hosting.Lifetime": "Information"
#     }
#   },
#     "Token": {
#         "TokenAudience": "8adf8e6e-67b2-4cf2-a259-e3dc5476c621",
#         "TokenIssuer": "https://sts.windows.net/<tenant_id>/",
#         "IssuerSigningKey": "0ofmokgw6do9edfwkxb0w7mcudpbbqu3",
#         "TokenLifetimeInMins": "120"
#     },
#   "AllowedHosts": "*"
# }
